/*
# Add qr_codes table

## Purpose
Persists QR codes generated by the user so they survive page reloads.
Previously QR codes were only in React state and lost on refresh, and
scan counts were fake (35% of card views).

## New Table
- `qr_codes`
  - `id` (uuid, primary key)
  - `card_id` (uuid, references cards.id ON DELETE CASCADE)
  - `label` (text)
  - `scans` (integer, default 0)
  - `created_at` (timestamptz, default now())

## Security
- RLS enabled, single-tenant no-auth app → `TO anon, authenticated`.
*/

CREATE TABLE IF NOT EXISTS qr_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  card_id uuid NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  label text NOT NULL,
  scans integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE qr_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_qr_codes" ON qr_codes;
CREATE POLICY "anon_select_qr_codes" ON qr_codes FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_qr_codes" ON qr_codes;
CREATE POLICY "anon_insert_qr_codes" ON qr_codes FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_qr_codes" ON qr_codes;
CREATE POLICY "anon_update_qr_codes" ON qr_codes FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_qr_codes" ON qr_codes;
CREATE POLICY "anon_delete_qr_codes" ON qr_codes FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_qr_codes_card_id ON qr_codes(card_id);
